14.0 t005086
open-synergy/ssi-stock pull request #26
Opened 2023-11-28 09:54 UTC by Miftahussalam

2023-12-11 23:32 UTC, andhit-r requested changes

2023-12-11 23:32 UTC, andhit-r commented on ssi_stock/models/stock_move_line.py
> +    def _action_cancel_done(self):
Mas sepertinya fungsi ini harus ditambahkan agar kode tidak dijalankan apabila stock.move.line tidak memiliki lot_id

2023-12-18 01:54 UTC, andhit-r requested changes

2023-12-18 01:54 UTC, andhit-r commented on ssi_stock/models/stock_move_line.py
> +                                                 package_id=ml.result_package_id, owner_id=ml.owner_id)
Mas @Miftahussalam , maksud saya apabila stock.move.line tidak memiliki nilai pada lot_id maka kode di atas akan error. Saya belum cek lagi sepertinya result_package_id dan owner_id juga tidak required

2023-12-18 09:27 UTC, Miftahussalam commented on ssi_stock/models/stock_move_line.py
> +                                                 package_id=ml.result_package_id, owner_id=ml.owner_id)
Tidak error mas @andhit-r kalau lot_id, package, owner tidak diisi maka nilainya False. Sudah saya tes, itu fungsi bawaan odoo. Bawaannya juga pakai parameter lot_id dll padahal belum tentu fields2 tersebut ada isinya

2024-01-06 09:21 UTC, andhit-r approved these changes

2024-01-06 09:22 UTC, andhit-r commented
/ocabot merge minor

2024-01-06 09:25 UTC, merged